[tool.poetry]
name = "python-ia"
version = "0.1.0"
description = ""
authors = ["GuilhermeKulkamp <guilhermekulkamp@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ollama = "^0.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
